//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_nhom.Model
{
    using System;
    using System.Collections.Generic;
    using sql_nhom.ViewModel;

    public partial class ChiTietNhacTra : BaseViewModel
    {
        private string _MaSach;
        public string MaSach { get => _MaSach; set { _MaSach = value; OnPropertyChanged(); } }

        private int _SoPhieu;
        public int SoPhieu { get => _SoPhieu; set { _SoPhieu = value; OnPropertyChanged(); } }

        private Nullable<decimal> _DonGiaPhat;
        public Nullable<decimal> DonGiaPhat { get => _DonGiaPhat; set { _DonGiaPhat = value; OnPropertyChanged(); } }

        private Sach _Sach;
        public virtual Sach Sach { get => _Sach; set { _Sach = value; OnPropertyChanged(); } }

        private PhieuNhacTra _PhieuNhacTra;
        public virtual PhieuNhacTra PhieuNhacTra { get => _PhieuNhacTra; set { _PhieuNhacTra = value; OnPropertyChanged(); } }

        
    }
}
