//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_nhom.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhacTra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhacTra()
        {
            this.ChiTietNhacTras = new HashSet<ChiTietNhacTra>();
        }
    
        public decimal SoPhieu { get; set; }
        public string MaThe { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhacTra> ChiTietNhacTras { get; set; }
        public virtual TheThuVien TheThuVien { get; set; }
    }
}
