//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_nhom.Model
{
    using System;
    using System.Collections.Generic;
    using sql_nhom.ViewModel;

    public partial class Sach : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sach()
        {
            this.ChiTietNhacTras = new HashSet<ChiTietNhacTra>();
            this.ChiTietPhieuMuons = new HashSet<ChiTietPhieuMuon>();
        }

        private string _MaSach;
        public string MaSach { get => _MaSach; set { _MaSach = value; OnPropertyChanged(); } }

        private string _MaTL;
        public string MaTL { get => _MaTL; set { _MaTL = value; OnPropertyChanged(); } }

        private string _MaNXB;
        public string MaNXB { get => _MaNXB; set { _MaNXB = value; OnPropertyChanged(); } }

        private string _MaTG;
        public string MaTG { get => _MaTG; set { _MaTG = value; OnPropertyChanged(); } }

        private string _TenSach;
        public string TenSach { get => _TenSach; set { _TenSach = value; OnPropertyChanged(); } }

        private string _TinhTrang;
        public string TinhTrang { get => _TinhTrang; set { _TinhTrang = value; OnPropertyChanged(); } }

        private Nullable<int> _NamXB;
        public Nullable<int> NamXB { get => _NamXB; set { _NamXB = value; OnPropertyChanged(); } }

        
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietNhacTra> ChiTietNhacTras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhieuMuon> ChiTietPhieuMuons { get; set; }
       

        private NhaXuatBan _NhaXuatBan;
        public virtual NhaXuatBan NhaXuatBan { get => _NhaXuatBan; set { _NhaXuatBan = value; OnPropertyChanged(); } }

        private TacGia _TacGia;
        public virtual TacGia TacGia { get => _TacGia; set { _TacGia = value; OnPropertyChanged(); } }

        private TheLoai _TheLoai;
        public virtual TheLoai TheLoai { get => _TheLoai; set { _TheLoai = value; OnPropertyChanged(); } }
    }
}
