//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sql_nhom.Model
{
    using System;
    using System.Collections.Generic;
    using sql_nhom.ViewModel;

    public partial class TheThuVien : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheThuVien()
        {
            this.PhieuMuons = new HashSet<PhieuMuon>();
            this.PhieuNhacTras = new HashSet<PhieuNhacTra>();
        }

        private string _MaThe;
        public string MaThe { get => _MaThe; set { _MaThe = value; OnPropertyChanged(); } }

        private string _MaDG;
        public string MaDG { get => _MaDG; set { _MaDG = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _NgayTao;
        public Nullable<System.DateTime> NgayTao { get => _NgayTao; set { _NgayTao = value; OnPropertyChanged(); } }

        private DocGia _DocGia;
        public virtual DocGia DocGia { get => _DocGia; set { _DocGia = value; OnPropertyChanged(); } }

        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuMuon> PhieuMuons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuNhacTra> PhieuNhacTras { get; set; }
    }
}
